### PR TITLE
Fix issue #421

### LINKED ISSUE #421: Inconsistency between tuple types and record types
The behaviour of record types changes depending on whether their labels are tuple-like or not

eg:
```fathom
let fst = fun (A: Type) (B: Type) (p: {x: A, y: B}) => p.x;
```
elaborates to
```fathom
let fst : fun (A : Type) (B : Type) -> { x : A, y : B } -> A = fun A B p => p.x;
```

but
```fathom
let fst = fun (A: Type) (B: Type) (p: {_0: A, _1: B}) => p._0;
```
elaborates to
```fathom
let fst : fun (A : Type) (B : Type) -> (A, A) -> A = fun A B p => p._0
```
note the pair is incorrectly displayed as `(A, A)` instead of `(A, B)`

### PR DESCRIPTION
**Pull request by Kmeakin**
- The issue was in distillation: we didn't push labels while distilling dependent tuples.

- Fixed a bug in the caching of tuple labels: `get_tuple_label` would not grow the `tuple_labels` vector, so `tuple_labels` would always be empty! This didn't affect correctness, but it did mean there was no performance improvement. 

- Added `get_tuple_labels` for getting a whole slice of tuple labels at once, and used it to optimize the implementation of `is_tuple_labels` 

Fixes #421

### CODE REVIEW

**Comment by brendanzab** [comment]
Oh, woops! Did I introduce this?

File: fathom/src/source.rs [hunk 1]
```diff
@@ -53,7 +72,7 @@ impl StringInterner {
 
     /// Returns true if `labels` is a sequence of tuple labels: `_0`, `_1`, ...
     pub fn is_tuple_labels(&mut self, labels: &[StringId]) -> bool {
-        (labels.iter().enumerate()).all(|(index, label)| self.is_tuple_label(index, *label))
+        labels == self.get_tuple_labels(0..labels.len())
     }
```
Comment (brendanzab) [inline fathom/src/source.rs:76]: Cool idea!

**Comment by brendanzab** [comment]
Looks good, thanks for catching this!
